name = "ss_0422"
type = "javascript"
account_id = '021058b6c0c0f10cadb9cb65ac74ac2e'
zone_id = '12df6b4371bafb22a185560b300cd791'
routes = ["kaalin.dev/*"]
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-04-10"

[site]
bucket = "./dist"
entry-point = "./"

[build]
command=""
upload.format ="service-worker"
