name = "ss_0422"
account_id = '021058b6c0c0f10cadb9cb65ac74ac2e'
routes = ["kaalin.dev/*"]
usage_model = 'unbound'
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-04-10"
main='dist/server.js'

[build]
command='pnpm build'

